import type { OrderChatMessage, OrderChatThread } from '@/types/chat';
import type { Order } from '@/types/order';
import type { Product } from '@/types/product';
import type { User, UserRole } from '@/types/user';

const now = Date.now();

function hoursAgo(hours: number) {
  return new Date(now - hours * 60 * 60 * 1000).toISOString();
}

function daysAgo(days: number) {
  return new Date(now - days * 24 * 60 * 60 * 1000).toISOString();
}

function daysFromNow(days: number) {
  return new Date(now + days * 24 * 60 * 60 * 1000).toISOString();
}

export const demoUsersByRole: Record<UserRole, User> = {
  customer: {
    branchAddress: null,
    branchId: null,
    branchName: null,
    id: 'demo-customer',
    linkedFranchiseIds: null,
    name: 'Ainur S.',
    phoneNumber: '+77070000001',
    productionUnitId: null,
    productionUnitName: null,
    role: 'customer',
  },
  franchisee: {
    branchAddress: '12 Kabanbay Batyr Ave, Astana',
    branchId: 'astana-flagship',
    branchName: 'AVISHU Astana Boutique',
    id: 'avishu-franchise-astana',
    linkedFranchiseIds: ['avishu-franchise-astana'],
    name: 'AVISHU Astana',
    phoneNumber: '+77070000002',
    productionUnitId: null,
    productionUnitName: null,
    role: 'franchisee',
  },
  production: {
    branchAddress: null,
    branchId: null,
    branchName: null,
    id: 'avishu-production-floor',
    linkedFranchiseIds: ['avishu-franchise-astana'],
    name: 'AVISHU Atelier',
    phoneNumber: '+77070000003',
    productionUnitId: 'atelier-core',
    productionUnitName: 'AVISHU Atelier Core',
    role: 'production',
  },
};

export const roleDescriptions: Record<UserRole, string> = {
  customer: 'A curated AVISHU storefront with orders, delivery, support chat, and profile in one calm shell.',
  franchisee: 'A boutique-facing desk for accepting orders, coordinating clients, and sending work into production.',
  production: 'A workshop surface for queue control, active tasks, and clean completion updates.',
};

export const demoRoleLabels: Record<UserRole, string> = {
  customer: 'Customer',
  franchisee: 'Franchisee',
  production: 'Production',
};

export const demoWalkthroughSteps = [
  'Customer places an order from the product screen.',
  'Franchisee accepts it and sends it into production.',
  'Production completes the task and marks it ready.',
  'Franchisee sends the ready order to delivery.',
  'Customer sees the updated tracker and support thread.',
] as const;

export const demoProducts: Product[] = [
  {
    availability: 'in_stock',
    category: 'NEW',
    colors: [
      { id: 'bone', label: 'Bone', swatch: '#D8D4CB' },
      { id: 'ash', label: 'Ash', swatch: '#C7C4BD' },
    ],
    collection: 'ALL.INN',
    description: 'A relaxed AVISHU tee cut for a clean oversized silhouette and everyday layering.',
    fit: 'Relaxed oversized fit',
    id: 'product-all-inn-tee',
    imageUrl: 'https://avishu.kz/wp-content/uploads/2025/12/ALLINN_wh3.webp',
    material: 'Dense cotton jersey',
    name: 'ALL.INN Tee',
    price: 24500,
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
  },
  {
    availability: 'in_stock',
    category: 'OUTERWEAR',
    colors: [
      { id: 'graphite', label: 'Graphite', swatch: '#4A4A4A' },
      { id: 'stone', label: 'Stone', swatch: '#B4AEA4' },
    ],
    collection: 'AUSH',
    description: 'Soft fleece layers composed as a coordinated set with a sculpted, winter-ready profile.',
    fit: 'Relaxed set with structured shoulder',
    id: 'product-aush-set',
    imageUrl: 'https://avishu.kz/wp-content/uploads/2025/12/IMG_0335-1.webp',
    material: 'Brushed fleece blend',
    name: 'AUSH Fleece Set',
    price: 54200,
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    availability: 'in_stock',
    category: 'BASICS',
    colors: [
      { id: 'coffee', label: 'Coffee', swatch: '#7C6654' },
      { id: 'chalk', label: 'Chalk', swatch: '#D8D5CE' },
    ],
    collection: 'SKIN',
    description: 'A slim long sleeve designed for close layering, soft structure, and quiet tonal styling.',
    fit: 'Close-to-body fit',
    id: 'product-skin-longsleeve',
    imageUrl: 'https://avishu.kz/wp-content/uploads/2025/12/SKIN-cofee_1.webp',
    material: 'Stretch jersey',
    name: 'SKIN Longsleeve',
    price: 22000,
    sizes: ['XS', 'S', 'M', 'L'],
  },
  {
    availability: 'preorder',
    category: 'CARDIGANS / KNIT',
    colors: [
      { id: 'mist', label: 'Mist', swatch: '#C8C7C2' },
      { id: 'graphite', label: 'Graphite', swatch: '#53514D' },
    ],
    collection: 'LOOM',
    description: 'A dense knit cardigan with a quiet drape, developed for made-to-order production.',
    fit: 'Soft straight fit',
    id: 'product-loom-cardigan',
    imageUrl: 'https://avishu.kz/wp-content/uploads/2025/11/LOOM_grey1.webp',
    material: 'Heavy knit blend',
    name: 'LOOM Cardigan',
    preorderLeadDays: 10,
    price: 32000,
    sizes: ['S', 'M', 'L'],
  },
  {
    availability: 'preorder',
    category: 'TROUSERS',
    colors: [
      { id: 'ink', label: 'Ink', swatch: '#34363A' },
      { id: 'cement', label: 'Cement', swatch: '#B9B6AE' },
    ],
    collection: 'EVO',
    description: 'Tailored trousers cut with a clean line and produced in a limited preorder window.',
    fit: 'Straight tailored leg',
    id: 'product-evo-trousers',
    imageUrl: 'https://avishu.kz/wp-content/uploads/2025/04/IMG_0335-1.webp',
    material: 'Structured suiting blend',
    name: 'EVO Trousers',
    preorderLeadDays: 12,
    price: 27200,
    sizes: ['XS', 'S', 'M', 'L'],
  },
  {
    availability: 'in_stock',
    category: 'SKIRTS',
    colors: [
      { id: 'black', label: 'Black', swatch: '#111111' },
      { id: 'pearl', label: 'Pearl', swatch: '#E0DDD6' },
    ],
    collection: 'ALL.INN',
    description: 'A clean monochrome skirt with a sharp line that balances the softness of the collection.',
    fit: 'Straight column fit',
    id: 'product-all-inn-skirt',
    imageUrl: 'https://avishu.kz/wp-content/uploads/2025/12/ALL.INN_skirt-bl1.webp',
    material: 'Compact suiting knit',
    name: 'ALL.INN Skirt',
    price: 23500,
    sizes: ['XS', 'S', 'M', 'L'],
  },
];

export const demoOrders: Order[] = [
  {
    branchId: demoUsersByRole.franchisee.branchId ?? demoUsersByRole.franchisee.id,
    branchName: demoUsersByRole.franchisee.branchName ?? demoUsersByRole.franchisee.name,
    createdAt: hoursAgo(28),
    customerId: demoUsersByRole.customer.id,
    customerName: demoUsersByRole.customer.name,
    customerPhoneNumber: demoUsersByRole.customer.phoneNumber ?? null,
    delivery: {
      address: '12 Kabanbay Batyr Ave, Astana',
      mapPreviewLabel: 'Map preview available after courier confirmation.',
      method: 'city_courier',
      note: 'Call before arrival.',
    },
    franchiseId: demoUsersByRole.franchisee.id,
    id: 'AV-3101',
    preferredReadyDate: null,
    productCollection: demoProducts[0].collection,
    productId: demoProducts[0].id,
    productName: demoProducts[0].name,
    productPrice: demoProducts[0].price,
    productionNote: 'Packed and standing by for courier handoff.',
    productionNoteUpdatedAt: hoursAgo(6),
    status: 'out_for_delivery',
    timeline: {
      acceptedAt: hoursAgo(26),
      deliveredAt: null,
      inProductionAt: hoursAgo(24),
      outForDeliveryAt: hoursAgo(2),
      placedAt: hoursAgo(28),
      readyAt: hoursAgo(6),
    },
    type: 'purchase',
    updatedAt: hoursAgo(2),
  },
  {
    branchId: demoUsersByRole.franchisee.branchId ?? demoUsersByRole.franchisee.id,
    branchName: demoUsersByRole.franchisee.branchName ?? demoUsersByRole.franchisee.name,
    createdAt: daysAgo(6),
    customerId: demoUsersByRole.customer.id,
    customerName: demoUsersByRole.customer.name,
    customerPhoneNumber: demoUsersByRole.customer.phoneNumber ?? null,
    delivery: {
      address: 'AVISHU Astana Boutique',
      mapPreviewLabel: null,
      method: 'boutique_pickup',
      note: 'Collected in store.',
    },
    franchiseId: demoUsersByRole.franchisee.id,
    id: 'AV-3092',
    preferredReadyDate: null,
    productCollection: demoProducts[5].collection,
    productId: demoProducts[5].id,
    productName: demoProducts[5].name,
    productPrice: demoProducts[5].price,
    productionNote: 'Completed and released to the boutique counter.',
    productionNoteUpdatedAt: daysAgo(5),
    status: 'delivered',
    timeline: {
      acceptedAt: daysAgo(6),
      deliveredAt: daysAgo(4),
      inProductionAt: daysAgo(5),
      outForDeliveryAt: null,
      placedAt: daysAgo(6),
      readyAt: daysAgo(5),
    },
    type: 'purchase',
    updatedAt: daysAgo(4),
  },
  {
    branchId: demoUsersByRole.franchisee.branchId ?? demoUsersByRole.franchisee.id,
    branchName: demoUsersByRole.franchisee.branchName ?? demoUsersByRole.franchisee.name,
    createdAt: hoursAgo(5),
    customerId: 'customer-north',
    customerName: 'Dana K.',
    customerPhoneNumber: '+7 705 530 10 04',
    delivery: {
      address: '29 Mangilik El Ave, Astana',
      mapPreviewLabel: 'Courier route will appear here.',
      method: 'express_courier',
      note: 'Deliver after 18:00.',
    },
    franchiseId: demoUsersByRole.franchisee.id,
    id: 'AV-3104',
    preferredReadyDate: daysFromNow(10),
    productCollection: demoProducts[3].collection,
    productId: demoProducts[3].id,
    productName: demoProducts[3].name,
    productPrice: demoProducts[3].price,
    productionNote: null,
    productionNoteUpdatedAt: null,
    status: 'placed',
    timeline: {
      acceptedAt: null,
      deliveredAt: null,
      inProductionAt: null,
      outForDeliveryAt: null,
      placedAt: hoursAgo(5),
      readyAt: null,
    },
    type: 'preorder',
    updatedAt: hoursAgo(5),
  },
  {
    branchId: demoUsersByRole.franchisee.branchId ?? demoUsersByRole.franchisee.id,
    branchName: demoUsersByRole.franchisee.branchName ?? demoUsersByRole.franchisee.name,
    createdAt: hoursAgo(9),
    customerId: 'customer-west',
    customerName: 'Elmira N.',
    customerPhoneNumber: '+7 705 530 10 05',
    delivery: {
      address: 'AVISHU Almaty Boutique',
      mapPreviewLabel: null,
      method: 'boutique_pickup',
      note: 'Size confirmation in store.',
    },
    franchiseId: demoUsersByRole.franchisee.id,
    id: 'AV-3105',
    preferredReadyDate: null,
    productCollection: demoProducts[2].collection,
    productId: demoProducts[2].id,
    productName: demoProducts[2].name,
    productPrice: demoProducts[2].price,
    productionNote: 'Ticket printed. Waiting on first workstation handoff.',
    productionNoteUpdatedAt: hoursAgo(2),
    status: 'accepted',
    timeline: {
      acceptedAt: hoursAgo(3),
      deliveredAt: null,
      inProductionAt: null,
      outForDeliveryAt: null,
      placedAt: hoursAgo(9),
      readyAt: null,
    },
    type: 'purchase',
    updatedAt: hoursAgo(3),
  },
  {
    branchId: demoUsersByRole.franchisee.branchId ?? demoUsersByRole.franchisee.id,
    branchName: demoUsersByRole.franchisee.branchName ?? demoUsersByRole.franchisee.name,
    createdAt: hoursAgo(20),
    customerId: 'customer-south',
    customerName: 'Madina A.',
    customerPhoneNumber: '+7 705 530 10 06',
    delivery: {
      address: '19 Dostyk Ave, Almaty',
      mapPreviewLabel: 'Delivery route shared once the order leaves the boutique.',
      method: 'city_courier',
      note: null,
    },
    franchiseId: demoUsersByRole.franchisee.id,
    id: 'AV-3106',
    preferredReadyDate: daysFromNow(12),
    productCollection: demoProducts[4].collection,
    productId: demoProducts[4].id,
    productName: demoProducts[4].name,
    productPrice: demoProducts[4].price,
    productionNote: 'Final stitch pass is next, then steam and QC.',
    productionNoteUpdatedAt: hoursAgo(1),
    status: 'in_production',
    timeline: {
      acceptedAt: hoursAgo(10),
      deliveredAt: null,
      inProductionAt: hoursAgo(2),
      outForDeliveryAt: null,
      placedAt: hoursAgo(20),
      readyAt: null,
    },
    type: 'preorder',
    updatedAt: hoursAgo(2),
  },
  {
    branchId: demoUsersByRole.franchisee.branchId ?? demoUsersByRole.franchisee.id,
    branchName: demoUsersByRole.franchisee.branchName ?? demoUsersByRole.franchisee.name,
    createdAt: hoursAgo(16),
    customerId: 'customer-east',
    customerName: 'Aruzhan T.',
    customerPhoneNumber: '+7 705 530 10 07',
    delivery: {
      address: 'AVISHU Astana Boutique',
      mapPreviewLabel: null,
      method: 'boutique_pickup',
      note: 'Franchisee pickup after noon.',
    },
    franchiseId: demoUsersByRole.franchisee.id,
    id: 'AV-3107',
    preferredReadyDate: daysFromNow(4),
    productCollection: demoProducts[1].collection,
    productId: demoProducts[1].id,
    productName: demoProducts[1].name,
    productPrice: demoProducts[1].price,
    productionNote: 'QC complete. Waiting for franchisee delivery handoff.',
    productionNoteUpdatedAt: hoursAgo(1),
    status: 'ready',
    timeline: {
      acceptedAt: hoursAgo(14),
      deliveredAt: null,
      inProductionAt: hoursAgo(11),
      outForDeliveryAt: null,
      placedAt: hoursAgo(16),
      readyAt: hoursAgo(1),
    },
    type: 'preorder',
    updatedAt: hoursAgo(1),
  },
];

export const demoChatThreads: OrderChatThread[] = [
  {
    branchId: demoUsersByRole.franchisee.branchId ?? demoUsersByRole.franchisee.id,
    branchName: demoUsersByRole.franchisee.branchName ?? demoUsersByRole.franchisee.name,
    customerId: demoUsersByRole.customer.id,
    customerName: demoUsersByRole.customer.name,
    customerPhoneNumber: demoUsersByRole.customer.phoneNumber ?? null,
    franchiseId: demoUsersByRole.franchisee.id,
    id: 'AV-3101',
    lastMessageAt: hoursAgo(1),
    lastMessageText: 'Courier is on the way and should arrive before 19:00.',
    orderId: 'AV-3101',
    orderStatus: 'out_for_delivery',
    productName: demoProducts[0].name,
    unreadCountForCustomer: 1,
    unreadCountForSupport: 0,
    updatedAt: hoursAgo(1),
  },
  {
    branchId: demoUsersByRole.franchisee.branchId ?? demoUsersByRole.franchisee.id,
    branchName: demoUsersByRole.franchisee.branchName ?? demoUsersByRole.franchisee.name,
    customerId: demoUsersByRole.customer.id,
    customerName: demoUsersByRole.customer.name,
    customerPhoneNumber: demoUsersByRole.customer.phoneNumber ?? null,
    franchiseId: demoUsersByRole.franchisee.id,
    id: 'AV-3092',
    lastMessageAt: daysAgo(4),
    lastMessageText: 'Thank you for visiting AVISHU. Your order is now complete.',
    orderId: 'AV-3092',
    orderStatus: 'delivered',
    productName: demoProducts[5].name,
    unreadCountForCustomer: 0,
    unreadCountForSupport: 0,
    updatedAt: daysAgo(4),
  },
  {
    branchId: demoUsersByRole.franchisee.branchId ?? demoUsersByRole.franchisee.id,
    branchName: demoUsersByRole.franchisee.branchName ?? demoUsersByRole.franchisee.name,
    customerId: 'customer-north',
    customerName: 'Dana K.',
    customerPhoneNumber: '+7 705 530 10 04',
    franchiseId: demoUsersByRole.franchisee.id,
    id: 'AV-3104',
    lastMessageAt: hoursAgo(5),
    lastMessageText: 'Your preorder is placed. Boutique confirmation is next.',
    orderId: 'AV-3104',
    orderStatus: 'placed',
    productName: demoProducts[3].name,
    unreadCountForCustomer: 0,
    unreadCountForSupport: 1,
    updatedAt: hoursAgo(5),
  },
  {
    branchId: demoUsersByRole.franchisee.branchId ?? demoUsersByRole.franchisee.id,
    branchName: demoUsersByRole.franchisee.branchName ?? demoUsersByRole.franchisee.name,
    customerId: 'customer-west',
    customerName: 'Elmira N.',
    customerPhoneNumber: '+7 705 530 10 05',
    franchiseId: demoUsersByRole.franchisee.id,
    id: 'AV-3105',
    lastMessageAt: hoursAgo(3),
    lastMessageText: 'Boutique confirmed the order and is preparing production transfer.',
    orderId: 'AV-3105',
    orderStatus: 'accepted',
    productName: demoProducts[2].name,
    unreadCountForCustomer: 1,
    unreadCountForSupport: 0,
    updatedAt: hoursAgo(3),
  },
  {
    branchId: demoUsersByRole.franchisee.branchId ?? demoUsersByRole.franchisee.id,
    branchName: demoUsersByRole.franchisee.branchName ?? demoUsersByRole.franchisee.name,
    customerId: 'customer-south',
    customerName: 'Madina A.',
    customerPhoneNumber: '+7 705 530 10 06',
    franchiseId: demoUsersByRole.franchisee.id,
    id: 'AV-3106',
    lastMessageAt: hoursAgo(2),
    lastMessageText: 'Your order has entered production.',
    orderId: 'AV-3106',
    orderStatus: 'in_production',
    productName: demoProducts[4].name,
    unreadCountForCustomer: 1,
    unreadCountForSupport: 0,
    updatedAt: hoursAgo(2),
  },
  {
    branchId: demoUsersByRole.franchisee.branchId ?? demoUsersByRole.franchisee.id,
    branchName: demoUsersByRole.franchisee.branchName ?? demoUsersByRole.franchisee.name,
    customerId: 'customer-east',
    customerName: 'Aruzhan T.',
    customerPhoneNumber: '+7 705 530 10 07',
    franchiseId: demoUsersByRole.franchisee.id,
    id: 'AV-3107',
    lastMessageAt: hoursAgo(1),
    lastMessageText: 'Your piece is ready. Boutique handoff is preparing pickup release.',
    orderId: 'AV-3107',
    orderStatus: 'ready',
    productName: demoProducts[1].name,
    unreadCountForCustomer: 1,
    unreadCountForSupport: 0,
    updatedAt: hoursAgo(1),
  },
];

export const demoChatMessages: OrderChatMessage[] = [
  {
    createdAt: hoursAgo(28),
    id: 'msg-3101-1',
    orderId: 'AV-3101',
    senderId: 'avishu-support',
    senderName: 'AVISHU Care',
    senderRole: 'support',
    text: 'Your order is placed. Boutique confirmation is in progress.',
  },
  {
    createdAt: hoursAgo(6),
    id: 'msg-3101-2',
    orderId: 'AV-3101',
    senderId: 'avishu-support',
    senderName: 'AVISHU Care',
    senderRole: 'support',
    text: 'The piece is ready and has been handed to the courier.',
  },
  {
    createdAt: hoursAgo(1),
    id: 'msg-3101-3',
    orderId: 'AV-3101',
    senderId: 'avishu-support',
    senderName: 'AVISHU Care',
    senderRole: 'support',
    text: 'Courier is on the way and should arrive before 19:00.',
  },
  {
    createdAt: daysAgo(6),
    id: 'msg-3092-1',
    orderId: 'AV-3092',
    senderId: demoUsersByRole.customer.id,
    senderName: demoUsersByRole.customer.name,
    senderRole: 'customer',
    text: 'Please prepare this one for boutique pickup.',
  },
  {
    createdAt: daysAgo(4),
    id: 'msg-3092-2',
    orderId: 'AV-3092',
    senderId: 'avishu-support',
    senderName: 'AVISHU Care',
    senderRole: 'support',
    text: 'Thank you for visiting AVISHU. Your order is now complete.',
  },
  {
    createdAt: hoursAgo(5),
    id: 'msg-3104-1',
    orderId: 'AV-3104',
    senderId: 'avishu-support',
    senderName: 'AVISHU Care',
    senderRole: 'support',
    text: 'Your preorder is placed. Boutique confirmation is next.',
  },
  {
    createdAt: hoursAgo(3),
    id: 'msg-3105-1',
    orderId: 'AV-3105',
    senderId: 'avishu-support',
    senderName: 'AVISHU Care',
    senderRole: 'support',
    text: 'Boutique confirmed the order and is preparing production transfer.',
  },
  {
    createdAt: hoursAgo(2),
    id: 'msg-3106-1',
    orderId: 'AV-3106',
    senderId: 'avishu-support',
    senderName: 'AVISHU Care',
    senderRole: 'support',
    text: 'Your order has entered production.',
  },
  {
    createdAt: hoursAgo(1),
    id: 'msg-3107-1',
    orderId: 'AV-3107',
    senderId: 'avishu-support',
    senderName: 'AVISHU Care',
    senderRole: 'support',
    text: 'Your piece is ready. Boutique handoff is preparing pickup release.',
  },
];

export const demoProfilePlaceholders = {
  savedAddresses: ['12 Kabanbay Batyr Ave, Astana', 'AVISHU Astana Boutique'],
  sizeProfile: 'Size profile will store preferred fit, height, and boutique notes in a later batch.',
};
